//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calatorie.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\\\MSSQLLocalDB;AttachDbFilename=\'C:\\\\Users\\\\irina\\\\documents" +
            "\\\\visual studio 2015\\\\Projects\\\\Calatorie\\\\Calatorie\\\\DBTimpSpatiu.mdf\';Integrat" +
            "ed Security=True")]
        public string DBTimpSpatiuConnectionString {
            get {
                return ((string)(this["DBTimpSpatiuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localDb)\\MSSQLLocalDb;Initial Catalog=\"C:\\USERS\\IRINA\\DOCUMENTS\\VISU" +
            "AL STUDIO 2015\\PROJECTS\\CALATORIE\\CALATORIE\\DBTIMPSPATIU.MDF\";Integrated Securit" +
            "y=True")]
        public string DBTIMPSPATIU_MDFConnectionString {
            get {
                return ((string)(this["DBTIMPSPATIU_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocaldb;AttachDbFilename=|DataDirectory|\\DBTimpSpatiu." +
            "mdf;Integrated Security=True;User Instance=False;Context Connection=False")]
        public string DBTimpSpatiuConnectionString1 {
            get {
                return ((string)(this["DBTimpSpatiuConnectionString1"]));
            }
        }
    }
}
